### ISSUE TITLE
Add Project description

### ISSUE THREAD

**Issue by mxnemu** [sil-quirk/sil-q#3]
Hello, I'm currently packaging Sil for [GNU Guix](https://www.gnu.org/software/guix/) and consider to package sil-q along with it, since I saw a lot of people playing it recently.
It would be nice if the README had a description of the goal of this project and how it is different from Sil.
Is Sil still in development, or is this a continuation fork in the spirit of Sil?

**Comment by sil-quirk** [comment]
Hi,

Sil-Q is heading towards its first official release and I am (slightly
grudgingly) writing the manual detailing its different behaviour.

I can update the readme also of course. What kind of timescale are you
working to?

This is a continuation fork in the spirit of Sil, since Sil hasn't been
updated in some time.

Peter

**Comment by Nehmulos** [comment]
Thanks for the clarification.
> What kind of timescale are you working to?
Guix is currently on rolling release, so there is no need to hurry. I still need to fix some bugs with the tutorial being looked up from the wrong place when I define PRIVATE_USER_PATH, and where it tries to write data/ files to a readonly install directory. I might send you some patches when I'm done with that.

Thanks for your continued work on Sil-Q!

**Comment by mxnemu** [comment]
Thanks for your help and for merging my changes. I will submit a package of sil-q to guix once there is a stable release.

Happy Hacking!

**Comment by diedummydie** [comment]
I would still love to see a list of changes from vanilla Sil 1.3. Am I missing where that is, or is it hidden in different parts of the manual PDF?

**Comment by sil-quirk** [comment]
So, there is something of a list on the releases page itself: https://github.com/sil-quirk/sil-q/releases
however this has largely tracked from release to release and so some earlier changes have been entirely obsoleted by newer ones. 

The manual PDF covers much of the detail around changes of the skills and mechanics, and the releases page covers the broader evolution including new artifacts, monsters, etc. I may try to put together an updated changes.txt for the 1.4 release although this will likely be at a similar level of detail to previous changes.txt updates e.g. Sil 1.3's "large changes to the early game monsters" rather than a monster by monster update list.
