### ISSUE TITLE
Sil-Q 1.4.2 randomly crashes 

### ISSUE THREAD

**Issue by CryoLibrarian** [sil-quirk/sil-q#44]
Greetings, after a week of no problems my games started crashing. On attacking usually, the whole program just shuts down without error message or anything. 

 I don't know what changed and am unsure how to do a proper bug report on it, but obviously happy to help with diagnostics. 

Regards
[Isind.zip](https://github.com/sil-quirk/sil-q/files/5302706/Isind.zip)

**Comment by sil-quirk** [comment]
Hi. This looks like a Windows save file; I presume you're playing on Windows? What windows do you generally have open?

Any example of the things you do from this save file to provoke a crash would be great (e.g. is it possible on this floor, and what are you fighting when it crashes?). And when you say "my games started crashing", have you had this issue with other saves?

**Comment by CryoLibrarian** [comment]
Right. I play on Win 10. That attached safefile crashes reliably for me, after I change the level. It does this whether I go up- or downstairs. I'll play with it a bit more to find exact crash circumstances later. 

Openened windows: in addition to main, I have inventory, equipment, message history, rolls, and recall open. 

Yes, after about a week of heavy normal operation most of my games have started crashing now. I feel its vaguely combat related but will test more and report back. 

Checking win error logs, I got a couple of 

"Exception code: 0xc0000005
Fault offset: 0x0000fec8
Faulting process ID: 0x1f84" 

for the SIL crashes.

**Comment by sil-quirk** [comment]
Managed a replication with the white wolves in the corridor to the north of the stairs, looking into it.

**Comment by sil-quirk** [comment]
So I'm fairly positive this one is down to the bug fixed in https://github.com/sil-quirk/sil-q/commit/ed33d3fba88b1c0963d46d2568a801579f546a47, just after the 1.4.2 release. Updating to that commit and building makes the crash go away, and so does disabling Follow-Through and heading into the same fight.

Sorry about this (I should release stable releases more frequently clearly, this last one has got very delayed for several reasons as it's got more and more ambitious) - but it should be fixable by toggling off one of Impale or Follow-Through I think.
