### ISSUE TITLE
1.5.0 beta2 - knowledge window bug?

### ISSUE THREAD

**Issue by davidk64fnq** [sil-quirk/sil-q#67]
![Sil-Q](https://user-images.githubusercontent.com/63939880/107595589-d6b86100-6c60-11eb-8e07-b044b8798486.jpg)
The 5th line should say "Dagger of Cuivienen"? When I press "r" with that line highlighted nothing happens.

**Comment by sil-quirk** [comment]
These show egos that can be applied to weapons of this type; you will note no icon corresponds to the ego on the far right.

I suspect this has been a mildly misleading interface since Sil 1.3, as it has never been the case in my experience of the game that the egos that apply to daggers also apply equally to shortswords and longswords. I may look at improving this at some point, but it's not high on my priority list.

**Comment by davidk64fnq** [comment]
Ah - I hadn't noticed the absence of an icon for that line. I thought it was telling me I had knowledge of the "Dagger of Cuivienen". Agree it's a bit confusing but not a high priority to fix. I only went looking at this area when I read about looking to see what potions one has found as a means of trying to work out what an unknown potion is. Thanks
