### ISSUE TITLE
sil-quirk community?

### ISSUE THREAD

**Issue by sherlach** [sil-quirk/sil-q#81]
Apologies in advance if this has been documented somewhere, but my searches haven't revealed anything.

I'm wondering if there are any active community/development forums for this (extremely underrated) game and fork? Would be nice if there was a community for discussing planned features in more detail, or offering up small fixes that other devs can try to implement in order to speed up development time... 

I also haven't found a wiki yet, and I'm willing to contribute to one to help net this game some exposure, if others think so too!

Love your work, sil-quirk, cheers!

**Comment by sil-quirk** [comment]
Angband.oook's Sil forum is historically the main place for discussion, quiet as it is: http://angband.oook.cz/forum/forumdisplay.php?f=12.
A few Sil-Q players can be found at https://angband.live which hosts the game so it can be played online and spectated.
Reddit's /r/roguelikes also has Sil discussions now and then.
I believe there's also a Discord - I will ask MicroChasm.

So far the game has survived on manual alone rather than wiki, though wikis are friendlier in the modern world and I would have no objection to someone starting one.

**Comment by sherlach** [comment]
Thanks for the reply, I can see some good stuff on that forum, although I don't really see myself doing more than just monitoring it anonymously. A Discord community would also be very useful and "friendlier in the modern world" too. For wikis, unless someone's willing/able to host a MediaWiki instance like [angband does](https://wiki.angband.live/index.php/Main_Page), the alternatives like fandom/wikia sites and github's inbuilt repo wiki seem somewhat unprofessional. 

Regardless, I think this is a very interesting project and it's worth getting people to contribute to a documentation effort.

(As a sidenote, I realise the angband main page references Sil-Q, but there's currently no dedicated page, could be nice to rectify that... just a little blurb and a link to the repo, perhaps? https://wiki.angband.live/index.php?title=Sil-Q&action=edit&redlink=1)

**Comment by sil-quirk** [comment]
Have put up a brief blurb and link as you suggested.

**Comment by sherlach** [comment]
Hey, with the recent manual update (1.5.0 - exciting!), I think there's a decent documentation depth for the game's current state of development. I'm happy to close this issue now if you want.
